sudo: required

language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.composer/vendor
        - $HOME/node_modules

before_script:
  - travis_retry nvm install node
  - travis_retry npm i -g npm
  - travis_retry composer self-update

install:
  - travis_retry composer install
  - travis_retry npm install

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - npm test

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
